/*! \file
    \brief Autogenerated enumerations (Umba Enum Gen)
 */

#pragma once


#include "marty_cpp/marty_enum.h"
#include "marty_cpp/marty_flag_ops.h"
#include "marty_cpp/marty_flags.h"

#include <exception>
#include <map>
#include <set>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>



namespace marty{
namespace lsp{

//#!MarkupKind
enum class MarkupKind : unsigned
{
    unknown     = (unsigned)(-1) /*!< ! */,
    invalid     = (unsigned)(-1) /*!< ! */,
    plainText   = 0x00000001 /*!<  */,
    markdown    = 0x00000002 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(MarkupKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( MarkupKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( MarkupKind::plainText   , "PlainText" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( MarkupKind::markdown    , "Markdown"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( MarkupKind::unknown     , "Unknown"   );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( MarkupKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( MarkupKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( MarkupKind::plainText   , "plain-text" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( MarkupKind::plainText   , "plain_text" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( MarkupKind::plainText   , "plaintext"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( MarkupKind::markdown    , "markdown"   );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( MarkupKind::unknown     , "invalid"    );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( MarkupKind::unknown     , "unknown"    );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( MarkupKind, std::map, 1 )


//#!ResourceOperationKind
enum class ResourceOperationKind : unsigned
{
    unknown   = (unsigned)(-1) /*!< ! */,
    invalid   = (unsigned)(-1) /*!< ! */,
    create    = 0x00000001 /*!<  */,
    rename    = 0x00000002 /*!<  */,
    delete_   = 0x00000003 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(ResourceOperationKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( ResourceOperationKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( ResourceOperationKind::delete_   , "Delete"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( ResourceOperationKind::rename    , "Rename"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( ResourceOperationKind::create    , "Create"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( ResourceOperationKind::unknown   , "Unknown" );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( ResourceOperationKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( ResourceOperationKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( ResourceOperationKind::delete_   , "delete"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( ResourceOperationKind::rename    , "rename"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( ResourceOperationKind::create    , "create"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( ResourceOperationKind::unknown   , "invalid" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( ResourceOperationKind::unknown   , "unknown" );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( ResourceOperationKind, std::map, 1 )


//#!FailureHandlingKind
enum class FailureHandlingKind : unsigned
{
    unknown     = (unsigned)(-1) /*!< ! */,
    invalid     = (unsigned)(-1) /*!< ! */,
    abort       = 0x00000001 /*!<  */,
    continue_   = 0x00000002 /*!<  */,
    undo        = 0x00000003 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(FailureHandlingKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( FailureHandlingKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FailureHandlingKind::undo        , "Undo"     );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FailureHandlingKind::continue_   , "Continue" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FailureHandlingKind::abort       , "Abort"    );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FailureHandlingKind::unknown     , "Unknown"  );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( FailureHandlingKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( FailureHandlingKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FailureHandlingKind::undo        , "undo"     );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FailureHandlingKind::continue_   , "continue" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FailureHandlingKind::abort       , "abort"    );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FailureHandlingKind::unknown     , "invalid"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FailureHandlingKind::unknown     , "unknown"  );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( FailureHandlingKind, std::map, 1 )


//#!DocumentDiagnosticReportKind
enum class DocumentDiagnosticReportKind : unsigned
{
    unknown     = (unsigned)(-1) /*!< ! */,
    invalid     = (unsigned)(-1) /*!< ! */,
    full        = 0x00000001 /*!<  */,
    unchanged   = 0x00000002 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(DocumentDiagnosticReportKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( DocumentDiagnosticReportKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( DocumentDiagnosticReportKind::unchanged   , "Unchanged" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( DocumentDiagnosticReportKind::full        , "Full"      );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( DocumentDiagnosticReportKind::unknown     , "Unknown"   );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( DocumentDiagnosticReportKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( DocumentDiagnosticReportKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( DocumentDiagnosticReportKind::unchanged   , "unchanged" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( DocumentDiagnosticReportKind::full        , "full"      );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( DocumentDiagnosticReportKind::unknown     , "invalid"   );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( DocumentDiagnosticReportKind::unknown     , "unknown"   );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( DocumentDiagnosticReportKind, std::map, 1 )


//#!TraceSetting
enum class TraceSetting : unsigned
{
    unknown    = (unsigned)(-1) /*!< ! */,
    invalid    = (unsigned)(-1) /*!< ! */,
    off        = 0x00000001 /*!<  */,
    messages   = 0x00000002 /*!<  */,
    verbose    = 0x00000003 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(TraceSetting)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( TraceSetting, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( TraceSetting::verbose    , "Verbose"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( TraceSetting::messages   , "Messages" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( TraceSetting::off        , "Off"      );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( TraceSetting::unknown    , "Unknown"  );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( TraceSetting, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( TraceSetting, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TraceSetting::verbose    , "verbose"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TraceSetting::messages   , "messages" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TraceSetting::off        , "off"      );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TraceSetting::unknown    , "invalid"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TraceSetting::unknown    , "unknown"  );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( TraceSetting, std::map, 1 )


//#!PositionEncodingKind
enum class PositionEncodingKind : unsigned
{
    unknown   = (unsigned)(-1) /*!< ! */,
    invalid   = (unsigned)(-1) /*!< ! */,
    utf8      = 0x00000001 /*!<  */,
    utf16     = 0x00000002 /*!<  */,
    utf32     = 0x00000003 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(PositionEncodingKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( PositionEncodingKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( PositionEncodingKind::utf32     , "Utf32"   );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( PositionEncodingKind::utf16     , "Utf16"   );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( PositionEncodingKind::utf8      , "Utf8"    );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( PositionEncodingKind::unknown   , "Unknown" );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( PositionEncodingKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( PositionEncodingKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( PositionEncodingKind::utf32     , "utf32"   );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( PositionEncodingKind::utf16     , "utf16"   );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( PositionEncodingKind::utf8      , "utf8"    );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( PositionEncodingKind::unknown   , "invalid" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( PositionEncodingKind::unknown   , "unknown" );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( PositionEncodingKind, std::map, 1 )


//#!TokenFormat
enum class TokenFormat : unsigned
{
    unknown    = (unsigned)(-1) /*!< ! */,
    invalid    = (unsigned)(-1) /*!< ! */,
    relative   = 0x00000001 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(TokenFormat)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( TokenFormat, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( TokenFormat::relative   , "Relative" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( TokenFormat::unknown    , "Unknown"  );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( TokenFormat, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( TokenFormat, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TokenFormat::relative   , "relative" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TokenFormat::unknown    , "invalid"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( TokenFormat::unknown    , "unknown"  );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( TokenFormat, std::map, 1 )


//#!FoldingRangeKind
enum class FoldingRangeKind : unsigned
{
    unknown   = (unsigned)(-1) /*!< ! */,
    invalid   = (unsigned)(-1) /*!< ! */,
    comment   = 0x00000001 /*!<  */,
    imports   = 0x00000002 /*!<  */,
    region    = 0x00000003 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(FoldingRangeKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( FoldingRangeKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FoldingRangeKind::region    , "Region"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FoldingRangeKind::imports   , "Imports" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FoldingRangeKind::comment   , "Comment" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FoldingRangeKind::unknown   , "Unknown" );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( FoldingRangeKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( FoldingRangeKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FoldingRangeKind::region    , "region"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FoldingRangeKind::imports   , "imports" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FoldingRangeKind::comment   , "comment" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FoldingRangeKind::unknown   , "invalid" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FoldingRangeKind::unknown   , "unknown" );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( FoldingRangeKind, std::map, 1 )


//#!FileOperationPatternKind
enum class FileOperationPatternKind : unsigned
{
    unknown   = (unsigned)(-1) /*!< ! */,
    invalid   = (unsigned)(-1) /*!< ! */,
    file      = 0x00000001 /*!<  */,
    folder    = 0x00000002 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(FileOperationPatternKind)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( FileOperationPatternKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FileOperationPatternKind::folder    , "Folder"  );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FileOperationPatternKind::file      , "File"    );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( FileOperationPatternKind::unknown   , "Unknown" );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( FileOperationPatternKind, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( FileOperationPatternKind, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FileOperationPatternKind::folder    , "folder"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FileOperationPatternKind::file      , "file"    );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FileOperationPatternKind::unknown   , "invalid" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( FileOperationPatternKind::unknown   , "unknown" );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( FileOperationPatternKind, std::map, 1 )


//#!WatchKind
enum class WatchKind : unsigned
{
    unknown   = (unsigned)(-1) /*!< ! */,
    invalid   = (unsigned)(-1) /*!< ! */,
    create    = 0x01 /*!<  */,
    change    = 0x02 /*!<  */,
    delete_   = 0x04 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(WatchKind)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( WatchKind, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( WatchKind::delete_   , "Delete"  );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( WatchKind::change    , "Change"  );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( WatchKind::create    , "Create"  );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( WatchKind::unknown   , "Unknown" );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( WatchKind, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( WatchKind, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( WatchKind::delete_   , "delete"  );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( WatchKind::change    , "change"  );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( WatchKind::create    , "create"  );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( WatchKind::unknown   , "invalid" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( WatchKind::unknown   , "unknown" );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( WatchKind, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_SERIALIZE_SET(WatchKind, std::set)

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_SET(WatchKind, std::set)


//#!SemanticTokenModifiers
enum class SemanticTokenModifiers : unsigned
{
    unknown          = (unsigned)(-1) /*!< ! */,
    invalid          = (unsigned)(-1) /*!< ! */,
    declaration      = 0x01 /*!<  */,
    definition       = 0x02 /*!<  */,
    readonly         = 0x04 /*!<  */,
    static_          = 0x08 /*!<  */,
    deprecated       = 0x10 /*!<  */,
    abstract         = 0x20 /*!<  */,
    async            = 0x40 /*!<  */,
    modification     = 0x80 /*!<  */,
    documentation    = 0x100 /*!<  */,
    defaultLibrary   = 0x200 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(SemanticTokenModifiers)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( SemanticTokenModifiers, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::async            , "Async"          );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::abstract         , "Abstract"       );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::defaultLibrary   , "DefaultLibrary" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::deprecated       , "Deprecated"     );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::modification     , "Modification"   );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::static_          , "Static"         );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::readonly         , "Readonly"       );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::definition       , "Definition"     );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::documentation    , "Documentation"  );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::declaration      , "Declaration"    );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( SemanticTokenModifiers::unknown          , "Unknown"        );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( SemanticTokenModifiers, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( SemanticTokenModifiers, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::async            , "async"           );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::abstract         , "abstract"        );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::abstract         , "abstract_"       );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::defaultLibrary   , "default-library" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::defaultLibrary   , "default_library" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::defaultLibrary   , "defaultlibrary"  );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::deprecated       , "deprecated"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::modification     , "modification"    );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::static_          , "static"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::static_          , "static_"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::readonly         , "readonly"        );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::definition       , "definition"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::documentation    , "documentation"   );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::declaration      , "declaration"     );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::unknown          , "invalid"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( SemanticTokenModifiers::unknown          , "unknown"         );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( SemanticTokenModifiers, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_SERIALIZE_SET(SemanticTokenModifiers, std::set)

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_SET(SemanticTokenModifiers, std::set)

} // namespace lsp
} // namespace marty

